version: '3.5'

volumes:
  db:
    driver: local

services:
  db:
    build:
      context: ./Docker
      dockerfile: postgresql.Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root_password
      - POSTGRES_DB=ecoekb
    ports: 
      - 5432:5432
    image: postgres:13.2-alpine
    volumes:
      - db:/var/lib/postgresql/data
    
  ecoeb-api:
    restart: always
    ports:
      - 5000:80
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  pgadmin:
  container_name: pgadmin4_container
  image: dpage/pgadmin4
  restart: always
  environment:
    PGADMIN_DEFAULT_EMAIL: tototo@mail.ru
    PGADMIN_DEFAULT_PASSWORD: 987654321
  ports:
    - "5050:80"
  depends_on:
    - db
